/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aditya;

import com.sun.media.sound.EmergencySoundbank;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author hp
 */


public class Desain extends javax.swing.JFrame {
    
    private int id = 0;
    private String code;
    private DefaultTableModel tbModel;
    private DefaultComboBoxModel cbModel;
    private ArrayList<Item> beli = new ArrayList<>();

    public Desain (){
        ComboItem comboItem = new ComboItem();
        this.cbModel = new DefaultComboBoxModel();
        
        TableTransaksi tabelModel = new TableTransaksi();
        this.tbModel = new DefaultTableModel(tabelModel.getKolomNama(),0);
          initComponents();
    }
    //penambahan id//
    private void incId(){
        this.id +=1;
    }
    
    //pengurangan id
    private void decId(){
        this.id-= 1;
    }
    
     
        
    //AddItem 
    private Object[] addItem(String nama,int jumlah){
        float harga = 0;
        ComboItem items = new ComboItem();
            for(int i= 0; i< items.getHargaBarang().size();i++){
                if(nama.equalsIgnoreCase(items.getJenisNama().get(i))){
                harga = items.getHargaBarang().get(i);
                }
            }
            Object[] obj ={
                nama,
                harga,
                jumlah
            };
            return obj;
    } 
    
    //set fungsi code
    private String setCode(){
        this.incId();
        //tanggal
        String sk = new SimpleDateFormat("yyMMdd").format(new Date());
        this.code = String.format(sk + "02d%", this.id);
        return code;
    }
    
    //update fungsi jumlah
    private void updateJumlah(String nama,int add){
        ArrayList<String> item = new ArrayList<>();
        for (int i = 0; i < tbModel.getRowCount(); i++){
            item.add(tbModel.getValueAt(i, 0).toString());
        }
        for (int i = 0; i < item.size();i++){
            if(item.get(i).equals(nama)){
                int jumlah = new Integer (tbModel.getValueAt(i, 2).toString());
                tbModel.setValueAt(jumlah + add, i, 2);
            }
        }
    }
    // melakukan penumpukan perhitungan item yang sudah ada
    private boolean Duplicate(String nama){
        boolean result = false;
        ArrayList<String> item = new ArrayList<>();
        for(int i = 0; i < tbModel.getRowCount();i++ ){
            item.add(tbModel.getValueAt(i, 0).toString());
        }
        for(String i : item){
            if(i.equals(nama)){
                result = true;
            }
        }
        return result;
    }
    
    private void beli(){
        if(isEmpty()){
            this.simpan.setEnabled(false);
            this.hapus.setEnabled(false);
        }else{
            this.simpan.setEnabled(true);
            this.hapus.setEnabled(true);
        }
    }
    
    //ngecek jika isi tabel kosong
    private boolean isEmpty(){
        return this.tblItem.getModel().getRowCount()<=0;
    }
    private void newTransaksi(){ 
      
        getCode.setEnabled(false);
        tambah.setEnabled(false);
        tblItem.setEnabled(false);
        hapus.setEnabled(false);
        getItem.setEnabled(false);
        simpan.setEnabled(false);
        jlhItem.setEnabled(false);
        keluar.setEnabled(false);
        tbModel.setRowCount(0);
        jlhItem.setText("");
        beli.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        getCode = new javax.swing.JTextField();
        jlhItem = new javax.swing.JTextField();
        getItem = new javax.swing.JComboBox<>();
        baru = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Code");

        jLabel2.setText("Item");

        getCode.setEnabled(false);
        getCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCodeActionPerformed(evt);
            }
        });

        jlhItem.setEnabled(false);

        getItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kopi", "Susu", "Gula" }));
        getItem.setSelectedIndex(-1);
        getItem.setEnabled(false);
        getItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getItemActionPerformed(evt);
            }
        });

        baru.setText("New");
        baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruActionPerformed(evt);
            }
        });

        tambah.setText("Add");
        tambah.setEnabled(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        tblItem.setModel(this.tbModel);
        jScrollPane1.setViewportView(tblItem);

        hapus.setText("Remove");
        hapus.setEnabled(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        simpan.setText("Save");
        simpan.setEnabled(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        keluar.setText("Cancel");
        keluar.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(simpan)
                                .addGap(18, 18, 18)
                                .addComponent(keluar)
                                .addGap(0, 158, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(getItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlhItem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getCode)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(baru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(getCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baru))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlhItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambah))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(keluar))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getItemActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String nama = this.getItem.getSelectedItem().toString();
        int jumlah = new Integer (this.jlhItem.getText());
        if (Duplicate(nama)){
            updateJumlah(nama, jumlah);
        }else{
            tbModel.addRow(addItem(nama, jumlah));  
        }
        this.beli();
    }//GEN-LAST:event_tambahActionPerformed

    private void getCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getCodeActionPerformed

    private void baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruActionPerformed
        // TODO add your handling code here:
        tambah.setEnabled(true);
        hapus.setEnabled(true);
        getItem.setEnabled(true);
        simpan.setEnabled(true);
        jlhItem.setEnabled(true);
        keluar.setEnabled(true); 
        baru.setEnabled(false);
        
        int i = 0;
        i++;
        
        Date d = new Date();
        SimpleDateFormat SDFormat = new SimpleDateFormat("yyMMdd");
        String dateString = SDFormat.format(d);
        
        getCode.setText(dateString +"0"+ i);
    }//GEN-LAST:event_baruActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        if(tblItem.getSelectedRow() <0){
            String sbr = "pilih item yang mau dihapus";
            JOptionPane.showInternalMessageDialog(this, sbr, "information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            int count = tblItem.getSelectedRows().length;
            for(int i = 0; i< count;i++){
                tbModel.removeRow(tblItem.getSelectedRow());
            }
        }
        this.beli();
    }//GEN-LAST:event_hapusActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try{
            // loop setiap tabel
            for(int i = 0; i < tbModel.getRowCount(); i++){
                //menyimpan nama dan jumlah menjadi variable
                String nama = tbModel.getValueAt(i, 0).toString();
                float harga = new Float(tbModel.getValueAt(i, 1).toString());
                int jumlah = new Integer(tbModel.getValueAt(i, 2).toString());
                this.beli.add(new Item(nama, harga, jumlah));
            }
            //Transaksi dengan kode dan comitted belanja
            Transaksi transaksi = new Transaksi(this.code, this.beli);
            //menangani output transaksi
            StringBuilder sbr = new StringBuilder();
            //menambahkan hasil transaksi
            sbr.append(transaksi.Pembayaran());
            // memanggil dialog
            JOptionPane.showMessageDialog(this, sbr, "Transaksi" , JOptionPane.INFORMATION_MESSAGE);
            // melakukan transaksi baru
            newTransaksi();
            
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baru;
    private javax.swing.JTextField getCode;
    private javax.swing.JComboBox<String> getItem;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jlhItem;
    private javax.swing.JButton keluar;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tblItem;
    // End of variables declaration//GEN-END:variables

    }
